### ISSUE TITLE
Register as an official provider/plugin

### ISSUE THREAD

**Issue by madAndroid** [carlpett/terraform-provider-sops#11]
Hi,

We're finding this incredibly useful, thank you for writing it!
Are there any plans to have this submitted as an "official" provider/plugin?

It would be preferable if there wasn't a separate install step required, and if Terraform could install it alongside all the other providers

**Comment by abeluck** [comment]
Also interested in this!

(here from mozilla/sops#292)

**Comment by vinay-ux** [comment]
I would be interested in this too , it will be super useful :)

**Comment by carlpett** [comment]
As an update, Hashicorp are currently in a 0.12-focus mode, so for the immediate future they aren't adding new official providers. This provider has been added to the list of community providers as a first step, but the approval to join the official providers is on hold until 0.12 is out an Hashicorp can dedicate some time on reviews again.
I'll keep this thread updated!

**Comment by Korijn** [comment]
Can't wait! Great stuff!

**Comment by pauln415** [comment]
Hi @carlpett, thank you for this Sops provider, we just started using it recently, and it is awesome and works great!

With 0.12 having been released for a few months now, have you considered resubmitting this as an official provider? I'm sure it would be used a lot more.

Thanks again!

**Comment by carlpett** [comment]
Hey @pauln415!
I did actually contact them again a couple of weeks after the release, but I haven't heard back. I'll shoot them a reminder :)

**Comment by abeluck** [comment]
Any movement on this? Anything I could help out with?

**Comment by carlpett** [comment]
Hey @abeluck,
I actually communicated with Hashicorp just a couple of days ago to see how things are moving. I got this reply:
>Unfortunately we are still working towards the release of providers in the registry. The provider source changes will be going into the 0.13 release planned for the next few months. 
>Sorry for the delay.

(Their plan is that 3rd party providers will be possible to upload somehow to the Terraform Registry which is right now just for modules)

**Comment by carlpett** [comment]
Hey all,
To update on this, there are good news! Community providers will be integrated in the Terraform Registry in Terraform 0.13, and I've enrolled this provider in the beta program :tada: 
There's some work to be done on my end to get this all automated and nice, but I've pushed 0.5.0 for Linux/amd64 manually, and tested it out. Looking forward to this! You can see the provider page [here](https://registry.terraform.io/providers/carlpett/sops).
Note that this will only work for 0.13 and up, so you'll need to update once it is released in order to use this. There's information about the beta program over in [Terraform issue #25016](https://github.com/hashicorp/terraform/issues/25016).

**Comment by abeluck** [comment]
@carlpett  :heart: many thanks for following up on this and keeping the momentum. This is great news.

**Comment by carlpett** [comment]
I'll close this issue since this appears to be working well now :)
