### ISSUE TITLE
Dependency github.com/hashicorp/vault/api v1.14.0 using older version

### ISSUE THREAD

**Issue by flamein** [carlpett/terraform-provider-sops#125]
The provider depends on an old version of the vault API, I assume because of the change to Business Source License in version 1.15.0.

How will you treat this one in the future?

**Comment by flamein** [comment]
actually... if I'm not mistaken: the api has a separate license: https://github.com/hashicorp/vault/blob/main/api/LICENSE which is MPL 2.0

**Comment by flamein** [comment]
Okay, now I started digging... and noticed this dependency is coming in through sops... which in the latest version depends on github.com/hashicorp/vault/api v1.15.0

so... I guess the question turns into: "when will support for the latest sops be added to the provider?"

To be clear, it's not that important for us, since we do not use the provider in conjunction with vault.

**Comment by carlpett** [comment]
Hi,
As you found out, the dependency comes from upstream. Since the process for releasing a new version of providers published to the Hashicorp registry involves a manual GPG signing step, I cannot automate version bump releases in a good way (that is, without putting my secret key somewhere, which sort of invalidates the point of the signing).

So releases typically happen when there's a bug fix or new feature that is important to someone. Let me know in that case and it'll likely happen quite fast :)
