### ISSUE TITLE
Nesting stopped working with Terraform v0.12

### ISSUE THREAD

**Issue by bfin** [carlpett/terraform-provider-sops#21]
The nested json/yaml example stopped working with Terraform v0.12. Root values continue to work as expected.

secret.json
```json
{
  "password": "foo",
  "db": {"password": "bar"}
}
```
main.tf
```tf
...
output "test" {
  value = data.sops_file.test.data.db.password
}
```

Output:
```
Error: Unsupported attribute

  on main.tf line 29, in output "test":
  29:   value = data.sops_file.test.data.db.password

This value does not have any attributes.
```

Version info:
  Provider v0.3.2
  Sops v3.2.0
  Terraform v0.11.14 (works)
  Terraform v0.12.2 (does NOT work)

**Comment by carlpett** [comment]
Hi @bfin,
Thanks for reporting! I'm a bit surprised this wasn't caught in tests. I'll need to investigate that closer.
As a workaround, you can treat `data` as a dictionary (because it is) and index into it like this: `data.sops_file.test.data["db.password"]`.

I've posted a question to Hashicorp if there is something I'm missing in the new APIs to enable the 0.11-compatible syntax again.

**Comment by bfin** [comment]
@carlpett Thanks for the workaround (and for your work on this provider)!

**Comment by carlpett** [comment]
Never updated here, apparently... The original behaviour was as unintended feature in Terraform core. There might be better support for richer data structures coming with later releases of TF, but for now this workaround is the best we'll get.
