### ISSUE TITLE
Question: What is the difference between sops_external and sops_file

### ISSUE THREAD

**Issue by davidovich** [carlpett/terraform-provider-sops#26]
I am confused about the use-cases of `sops_external` and `sops_file`. This may be due to my inexperience in terraform.

The documentation says that `sops_external` is used to *read files that might not be local*, but gives a `local_file` provider as an example (which is counter-intuitive). Also `sops_file` and `sops_external` examples are almost equivalent.

When would you use one or the other ?

**Comment by carlpett** [comment]
Hey @davidovich!
Yes, that example may be a bit unfortunate. `sops_external` is useful if you want to pass through the encrypted data so that it comes from another Terraform resource or datasource. So for example you might have a data source that reads the encrypted data blob from a Consul Key-Value store:
```hcl
data "consul_keys" "some-data" {
  key {
    name    = "mydata"
    path    = "service/my-app"
  }
}

data "sops_external" "demo-secret" {
  source     = data.consul_keys.some-data.var.mydata
  input_type = "yaml"
}
```

Does that make more sense?

**Comment by jacobfoard** [comment]
Hey there, I added in `sops_external` for my use case at work for reading in from a `aws_s3_bucket_object`. I see how the `local_file` is confusing, but I wanted to provide a simple way to show the functionality rather than require an additional provider that took configuration. 

It could definitely be more clear in the docs :).

**Comment by davidovich** [comment]
Thank you to you both, this clears the confusion.
